version: '3.7'

services:
  web:
    build: .
    command: sh -c 'python manage.py makemigrations --noinput &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery
      - rabbitmq

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  celery:
    build: .
    command: celery -A app worker -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
    environment:
      rabbitmq_uri: amqp://127.0.0.1:5672
    depends_on:
      - redis
      - db
      - rabbitmq

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13.0-rc.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_PLUGINS=rabbitmq_management
    depends_on:
      - db

    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"


volumes:
  postgres_data: