# Generated by Django 3.2.6 on 2023-12-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=128, verbose_name='Функция')),
                ('dt', models.IntegerField(verbose_name='Шаг t, часы')),
                ('interval', models.IntegerField(verbose_name='Интервал t, дней')),
                ('graph', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='График')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата обработки')),
            ],
            options={
                'verbose_name': 'функцию',
                'verbose_name_plural': 'функции',
            },
        ),
    ]
